import '../globals.css';
import '@mantine/core/styles.css';

import type { Metadata } from 'next';

import { theme } from '../theme';
import { Inter } from 'next/font/google';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';

import { TheHeader } from '@/components/TheHeader/TheHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>

      <body className={inter.className}>
        <MantineProvider defaultColorScheme="dark" theme={theme}>
          <TheHeader />

          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
